version: "4.3"

services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  backend_service:
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - mongo_db
  client_service:
    build: ./project
    ports:
      - 5173:5173
    depends_on:
      - mongo_db
      - backend_service

volumes:
  mongo_db: {}